---
# https://github.com/samba-in-kubernetes/sit-environment/issues/102
- name: Modify repositories to point at CentOS vault
  shell: >-
    find /etc/yum.repos.d/ -name '*.repo' -exec sed -i \
      -e 's|^mirrorlist=|#mirrorlist=|g' \
      -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' {} \;

- name: Process common OS tasks
  include_tasks: centos.yml
