---
- name: Create user
  user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    password: "{{ item.value.password | password_hash }}"
    group: "{{ item.value.primary_group | default(omit) }}"
    comment: "{{ item.value.comment | default(omit) }}"
    groups: "{{ item.value.groups | default(omit) }}"
    state: present
  with_items: "{{ accounts | dict2items }}"
