---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os[site.os].includes }}"
  loop_control:
    loop_var: include_file

- name: Process group accounts
  include_tasks: create_groups.yml
  vars:
    accounts: "{{ config.accounts[account_group].groups }}"
  when:
    - config.accounts[account_group].groups
    - account_group in site.accounts
  with_items: "{{ config.accounts }}"
  loop_control:
    loop_var: account_group

- name: Process user accounts
  include_tasks: create_users.yml
  vars:
    accounts: "{{ config.accounts[account_group].users }}"
  when:
    - config.accounts[account_group].users
    - account_group in site.accounts
  with_items: "{{ config.accounts }}"
  loop_control:
    loop_var: account_group
