---
- include_role:
    name: gluster.infra

- name: Enable firewall rules for gluster
  firewalld: service=glusterfs permanent=yes state=enabled

- name: Reload firewall
  command: firewall-cmd --reload

- name: Ensure glusterd service is enabled
  service: name=glusterd state=started enabled=yes
