---
- include_role:
    name: gluster.infra

- name: Enable firewall rules for gluster
  firewalld: service=glusterfs permanent=yes state=enabled

- name: Reload firewall
  command: firewall-cmd --reload

- name: Ensure glusterd service is enabled
  service: name=glusterd state=started enabled=yes

- include_tasks:
    file: new_volume.yml
  vars:
    volume:
      name: "{{ item.cluster_volume }}"
      type: "{{ item.glusterfs.type }}"
      backends: "{{ item.glusterfs.bricks }}"
      subvolume_size: "{{ item.glusterfs.subvolume_size }}"
      options: "{{ item.glusterfs.options }}"
  with_items: "{{ samba_shares }}"
