---
- name: Create Replicate Volumes
  gluster_volume:
    state: present
    name: "{{ name }}"
    bricks: "{{ volume.glusterfs.bricks }}"
    cluster: "{{ config.groups['cluster'] }}"
    replicas: "{{ volume.glusterfs.subvolume_size }}"
  run_once: yes
  when: volume.glusterfs.type == 'replicate'

- name: Create Dispersed Volumes
  gluster_volume:
    state: present
    name: "{{ name }}"
    bricks: "{{ volume.glusterfs.bricks }}"
    cluster: "{{ config.groups['cluster'] }}"
    disperses: "{{ volume.glusterfs.subvolume_size }}"
    force: yes
  run_once: yes
  when: volume.glusterfs.type == 'disperse'

- name: Set volume options
  gluster_volume:
    state: present
    name: "{{ name }}"
    options: "{{ volume.glusterfs.options }}"
  run_once: yes
  when: volume.glusterfs.options is defined

- name: Mount volume
  mount:
    path: "{{ path }}"
    src: "localhost:/{{ name }}"
    fstype: glusterfs
    opts: "{{ mount_opts | default(omit) }}"
    state: mounted
