---
ctdb_network_private_interfaces: >-
  {{
    config.nodes |
    dict2items |
    selectattr('value.groups', 'contains', 'cluster') |
    map(attribute='value.networks.private') |
    list
  }}
ctdb_network_public_interfaces: >-
  {{
    config.nodes |
    dict2items |
    selectattr('value.groups', 'contains', 'cluster') |
    map(attribute='value.ctdb.public') |
    list
  }}
ctdb_network_public_interface_subnet_mask: "24"
ctdb_network_public_interface_name: "eth2"

samba_netbios_name: "SIT-CEPHFS-TEST"

samba_shares:
  - name: share
    samba:
      options:
        "acl_xattr:security_acl_name": "user.NTACL"
  - name: share-cs
    samba:
      options:
        "acl_xattr:security_acl_name": "user.NTACL"
    cephfs:
      options:
        "casesensitive": yes
