---
ctdb_network_private_interfaces: >-
  {{
    config.nodes |
    dict2items |
    selectattr('value.groups', 'contains', 'cluster') |
    map(attribute='value.networks.private') |
    list
  }}
ctdb_network_public_interfaces: >-
  {{
    config.nodes |
    dict2items |
    selectattr('value.groups', 'contains', 'cluster') |
    map(attribute='value.ctdb.public') |
    list
  }}
ctdb_network_public_interface_subnet_mask: "24"
ctdb_network_public_interface_name: "eth2"

samba_netbios_name: "SIT-XFS-TEST"

samba_shares:
  - cluster_volume: "samba"
    share_name: "share"
    device: "/dev/vdb"
    samba:
      options:
        "acl_xattr:ignore system acls": "yes"
