---
- hosts: cluster
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
    - cluster-{{ config.be.name }}.yml
  roles:
    - common.prep
    - node.prep
    - "sit.{{ config.be.name }}"
    - role: samba.install
      when: config.samba
    - role: samba.setup
      when: config.samba
    - role: ctdb.setup
      when: config.samba
    - users.setup
