---
# Note: ceph-common package is only required to be able to mount the ceph volume
#       from the host. Cephadm will download all other required container images
#       independently of the repository.
- name: Install required packages
  yum:
    name:
      - podman
      - lvm2
      - ceph-common
    state: present

- name: Download cephadm
  get_url:
    url: "{{ ceph_shaman.json[0].url }}/noarch/cephadm"
    dest: /root/cephadm
    mode: 0755
