---
- name: Run smbd unconfined
  vars:
    smbd_fcontext: "{{ '/usr/bin/smbd' if config.os[site.os].version | int >= 10 else '/usr/sbin/smbd' }}"
  block:
    - name: Configure SElinux context for smbd
      sefcontext:
        target: "{{ smbd_fcontext }}"
        setype: bin_t
        state: present

    - name: Restore SElinux context
      command: restorecon /usr/sbin/smbd

- name: Temporarily allow access on smbd_var_run_t for ctdbd from SELinux
  include_tasks: custom_selinux_policy.yml
  vars:
    module_name: ctdbd_smbd_pid
