---
- name: Mount gluster volume using glusterfs
  mount:
    path: "{{ config.paths.mount }}/tmp-fuse"
    src: "{{ volume }}"
    fstype: glusterfs
    state: mounted

- name: Set permission of volume root to 0777
  file:
    path: "{{ config.paths.mount }}/tmp-fuse"
    mode: '0777'

- name: Unmount mounted fuse glusterfs mount
  mount:
    path: "{{ config.paths.mount }}/tmp-fuse"
    state: absent
