---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/glusterfs/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes

- name: Install samba-vfs-glusterfs package
  when: config.install.samba.repo is defined
  yum:
    name: samba-vfs-glusterfs
    state: present
