---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os[config.nodes[inventory_hostname].os].includes }}"
  loop_control:
    loop_var: include_file

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes

- name: Install samba-vfs-glusterfs package
  yum:
    name: samba-vfs-glusterfs
    state: present

- name: Mount glusterfs using fuse mount and set world writable permissions
  include_tasks:
    file: "glusterfs/fix_share_permissions.yml"
  vars:
    volume: "localhost:/{{ item.cluster_volume }}"
  with_items: "{{ samba_shares }}"
  run_once: true
