---
- name: Install python packages
  pip:
    state: latest
    name:
      - jmespath

- name: Install ansible roles
  community.general.ansible_galaxy_install:
    type: role
    dest: "{{ site_dir }}/ansible/roles"
    requirements_file: "{{ backend_dir }}/requirements.yml"
