---
- name: Create the XFS filesystem
  filesystem:
    dev: "{{ volume.xfs.device }}"
    force: false
    fstype: xfs

- name: Mount the XFS filesystem
  mount:
    path: "{{ path }}"
    src: "{{ volume.xfs.device }}"
    fstype: xfs
    state: mounted

- name: Set mount permissions
  file:
    path: "{{ path }}"
    mode: "{{ mode }}"
