- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os.includes }}"
  loop_control:
    loop_var: include_file

- name: Process backend specific tasks (server)
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: server/main.yml
