---
- name: Install ceph related samba packages
  when: inventory_hostname in groups['cluster']
  block:
    - name: Install VFS module
      yum:
        name: samba-vfs-cephfs
        state: present

    - name: Install CephFS proxy components
      yum:
        name:
          - libcephfs-proxy2
          - libcephfs-daemon
        state: present

    - name: Install CTDB RADOS helper
      when: config.data.ctdb_mutex == 'rados'
      yum:
        name: ctdb-ceph-mutex
        state: present
