---
- name: Install ceph related samba packages
  when: inventory_hostname in groups['cluster']
  block:
    - name: Install VFS module
      when: config.be.variant == 'vfs'
      yum:
        name: samba-vfs-cephfs
        state: present

    - name: Install CTDB RADOS helper
      when: config.data.ctdb_mutex == 'rados'
      yum:
        name: ctdb-ceph-mutex
        state: present
