---
- name: Setup Vagrant file
  run_once: true
  template:
    src: Vagrantfile.j2
    dest: Vagrantfile

- name: start vagrant vms
  run_once: true
  command: vagrant up --no-provision

- name: provision vagrant vms
  run_once: true
  command: vagrant provision

- name: Get IP address
  command: vagrant ssh {{ inventory_hostname }} -c "ip -j -4 addr show scope global"
  register: vm_ip

# Ansible implicitly runs this task as if it had:
#
#   delegate_to: localhost
#   run_once: true
- name: Update inventory
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ (hostvars[item].vm_ip.stdout | from_json)[0].addr_info[0].local }}"
  with_items: "{{ ansible_play_hosts }}"

- name: Create state directory structure on host
  run_once: true
  file:
    path: "{{ config.statedir }}/{{ item }}"
    state: directory
  loop: "{{ config.groups['cluster'] + config.groups['clients'] }}"

- name: Copy common playbook configuration
  run_once: true
  copy:
    src: ansible/config.yml
    dest: "{{ config.statedir }}"
