---
- name: Setup Vagrant file
  template:
    src: Vagrantfile.j2
    dest: "{{ config.home }}/Vagrantfile"

- name: start vagrant vms
  command:
    chdir: "{{ config.home }}"
    cmd: vagrant up --no-provision

- name: provision vagrant vms
  command:
    chdir: "{{ config.home }}"
    cmd: vagrant provision

- name: copy vagrant generated inventory file - local machine
  copy:
    src: "{{ config.home }}/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
    dest: "{{ config.home }}/site_inventory"

- name: adapt inventory - ssh options
  blockinfile:
    path: "{{ config.home }}/site_inventory"
    block: |
      [all:vars]
      ansible_ssh_common_args='-o StrictHostKeyChecking=no'

- name: copy vagrant generated inventory file - setup machine
  copy:
    src: "{{ config.home }}/site_inventory"
    dest: "{{ config.home }}/site_inventory_setup"

- name: adapt inventory - correct ssh key
  replace:
    path: "{{ config.home }}/site_inventory_setup"
    regexp: "ansible_ssh_private_key_file='.*/\\.vagrant\\.d/insecure_private_key'"
    replace: "ansible_ssh_private_key_file='insecure_private_ssh_key'"

- name: dump ssh config
  command:
    chdir: "{{ config.home }}"
    cmd: vagrant ssh-config
  register: output

- name: store ssh-config in file
  copy:
    content: "{{ output.stdout }}\n"
    dest: "{{ config.home }}/ssh-config-host"

- name: Create host alias
  lineinfile:
    path: "{{ config.home }}/ssh-config-host"
    state: present
    regexp: '^\s*Host\s+{{ config.groups[item][0] }}.*$'
    line: "Host {{ config.groups[item][0] }} {{ item }}"
  with_items: "{{ config.groups.keys() }}"

- name: copy ssh-config for setup
  copy:
    src: "{{ config.home }}/ssh-config-host"
    dest: "{{ config.home }}/ssh-config-setup"

- name: modify ssh-config-setup
  replace:
    path: "{{ config.home }}/ssh-config-setup"
    regexp: "IdentityFile .*"
    replace: "IdentityFile ansible/insecure_private_ssh_key"

- name: Create state directory structure on host
  file:
    path: "{{ config.statedir }}/{{ item }}"
    state: directory
  loop: "{{ config.groups['cluster'] + config.groups['clients'] }}"
