---
- name: Process common OS tasks
  include_tasks: centos.yml

- name: Install Python3.12 pip
  yum:
    name: python3.12-pip
    state: installed

- name: Install pip jinja2 library
  pip:
    executable: pip3.12
    name: jinja2
