---
- name: update packages
  yum:
    name: '*'
    state: latest

- name: Enable EPEL repository
  yum:
    name: epel-release
    state: latest

# RHEL 8 image doesn't include make
- name: Install additional packages
  yum:
    name: make
    state: installed

- name: Install Python3 pip
  yum:
    name: python3-pip
    state: installed

- name: Install pip jinja2 library
  pip:
    name: jinja2
