---
- name: Run tests
  shell:
    chdir: /root/sit-test-cases
    cmd: make test &> /var/log/test.out
  when: test_sanity_only is undefined

- name: Run sanity tests
  shell:
    chdir: /root/sit-test-cases
    cmd: make sanity_test &> /var/log/test.out
  when: test_sanity_only is defined
