---
- name: Run tests
  block:
    - command:
        chdir: /root/sit-test-cases
        cmd: make test
      register: test_output
    - debug: var=test_output.stdout_lines
  when: test_sanity_only is undefined

- name: Run sanity tests
  block:
    - command:
        chdir: /root/sit-test-cases
        cmd: make sanity_test
      register: test_output
    - debug: var=test_output.stdout_lines
  when: test_sanity_only is defined
