---
- name: Run tests
  block:
    - shell:
        chdir: /root/sit-test-cases
        cmd: make test &> /var/log/test.out
      register: test_output
    - debug: var=test_output.stdout_lines
  when: test_sanity_only is undefined

- name: Run sanity tests
  block:
    - shell:
        chdir: /root/sit-test-cases
        cmd: make sanity_test &> /var/log/test.out
      register: test_output
    - debug: var=test_output.stdout_lines
  when: test_sanity_only is defined
