---
- name: Install required packages
  yum:
    name:
      - cifs-utils
      - python3-pip
      - git
      - make
      - python3-pytest
      - podman
      - tox
      - sshfs
    state: latest

- name: Link to pytest
  file:
    src: /usr/bin/pytest-3
    dest: /usr/local/bin/pytest
    state: link
