---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os[config.nodes[inventory_hostname].os].includes }}"
  loop_control:
    loop_var: include_file

- name: Process backend specific tasks (client)
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: client/main.yml

- debug:
    msg: "{{ ctdb_network_public_interfaces }}"

- name: Create backend mount points
  file:
    path: "{{ config.paths.mount }}/backends/{{ item.share_name }}-{{ config.be.name }}-{{ config.be.variant }}"
    state: directory
  with_items: "{{ samba_shares }}"

- name: Make the backend filesystems accessible from the client
  command: >-
    sshfs -o reconnect
      root@{{ config.groups['cluster'][0] }}:{{ config.paths.mount }}/{{ item.cluster_volume }}
      {{ config.paths.mount }}/backends/{{ item.share_name }}-{{ config.be.name }}-{{ config.be.variant }}
  with_items: "{{ samba_shares }}"

- name: Create the test-info.yml file with test cluster information
  template:
    src: test-info.yml.j2
    dest: /root/test-info.yml
  vars:
    private_interfaces: "{{ ctdb_network_private_interfaces }}"
    public_interfaces: "{{ ctdb_network_public_interfaces }}"
    exported_sharenames: >-
      {{ samba_shares | map(attribute='share_name') |
      map('regex_replace', '$', '-' + config.be.name + '-' + config.be.variant) | list }}
    test_backend: "{{ config.be.name }}"
