---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/server/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file

# Pull ceph container image for all nodes
- name: Pull containers
  command: /root/cephadm pull
