- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - samba_load_libgfapi
    - samba_export_all_rw

- name: Install samba and samba-vfs-glusterfs packages
  yum:
    name: samba-vfs-glusterfs
    state: present

- name: Mount glusterfs using fuse mount and set world writable permissions
  include_tasks:
    file: "glusterfs.fix_share_permissions.yml"
  vars:
    volume: "localhost:/{{ item.cluster_volume }}"
  with_items: "{{ samba_shares }}"
  run_once: true
