---
- name: Mount XFS
  mount:
    path: "{{ path }}"
    src: "{{ volume }}"
    fstype: xfs
    state: mounted

- name: Set permission of volume root to 0777
  file:
    path: "{{ path }}"
    mode: '0777'
