---
# required for python3-pyxattr
- name: Enable CRB repo
  command: dnf config-manager --set-enabled crb

- name: Enable Samba nightly rpms repository
  command: >-
    yum-config-manager --add-repo
    http://artifacts.ci.centos.org/samba/pkgs/master/centos/samba-nightly-master.repo
