---
# required for python3-pyxattr
- name: Enable CRB repo
  command: dnf config-manager --set-enabled crb

- name: Enable Samba nightly rpms repository
  command: >-
    yum-config-manager --add-repo {{ config.install.samba.repo.url }}
  when: config.install.samba.repo is defined
