---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os[site.os].includes }}"
  loop_control:
    loop_var: include_file

- name: Process backend specific tasks (common)
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: common/main.yml

- name: Create /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
