---
- name: Process backend specific tasks
  when: inventory_hostname in groups['cluster']
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: logs/main.yml

- name: Extract journal since last boot
  shell: journalctl -xb -n all > /var/log/journal

- name: Extract dmesg contents
  shell: dmesg -T > /var/log/dmesg.kernel

- name: Copy /var/log directory
  synchronize:
    src: /var/log
    dest: "{{ config.statedir }}/{{ inventory_hostname }}"
    mode: pull
