---
# required for python3-pyxattr
- name: Enable PowerTools repo
  command: yum-config-manager --enable powertools

- name: Enable Samba nightly rpms repository
  command: >-
    yum-config-manager --add-repo
    http://artifacts.ci.centos.org/samba/pkgs/master/centos/samba-nightly-master.repo
