- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os.includes }}"
  loop_control:
    loop_var: include_file

- name: Process backend specific tasks (common)
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: common/main.yml

- name: create ansible directory (for ssh key)
  file:
    path: /home/vagrant/ansible
    state: directory

- name: copy ssh key
  copy:
    src: /home/vagrant/ansible/vagrant_insecure_private_ssh_key
    dest: /home/vagrant/ansible/vagrant_insecure_private_ssh_key

- name: copy ssh config
  copy:
    src: ssh-config-setup
    dest: /home/vagrant/.ssh/config

- name: Create /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
