---
- include_role:
    name: gluster.infra

- name: Enable firewall rules for gluster
  firewalld: service=glusterfs permanent=yes state=enabled

- name: Ensure glusterd service is enabled
  service: name=glusterd state=started enabled=yes

- include_tasks:
    file: new_volume.yml
  vars:
    volume:
      name: "{{ replicate_cluster_volume }}"
      type: "replicate"
      backends: "{{ replicate_cluster_bricks }}"
      replica_count: "{{ replicate_cluster_replica_count }}"
      options: "{{ replicate_cluster_options }}"

- include_tasks:
    file: new_volume.yml
  vars:
    volume:
      name: "{{ disperse_cluster_volume }}"
      type: "disperse"
      backends: "{{ disperse_cluster_bricks }}"
      disperse_count: "{{ disperse_cluster_disperse_count }}"
      options: "{{ disperse_cluster_options }}"
