---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/repo/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file

- name: Install backend specific packages
  include_role:
    name: "sit.{{ config.be.name }}"
    tasks_from: repo/main.yml
