---
- name: Setup Vagrant file
  run_once: true
  template:
    src: Vagrantfile.j2
    dest: "{{ site_dir }}/Vagrantfile"

- name: start vagrant vms
  run_once: true
  command: vagrant up --no-provision
  args:
    chdir: "{{ site_dir }}"

- name: provision vagrant vms
  run_once: true
  command: vagrant provision
  args:
    chdir: "{{ site_dir }}"

- name: Get IP address
  command: vagrant ssh {{ inventory_hostname }} -c "ip -j -4 addr show scope global"
  args:
    chdir: "{{ site_dir }}"
  register: vm_ip

# Ansible implicitly runs this task as if it had:
#
#   delegate_to: localhost
#   run_once: true
- name: Update inventory
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ (hostvars[item].vm_ip.stdout | from_json)[0].addr_info[0].local }}"
  with_items: "{{ ansible_play_hosts }}"
