---
- name: Prepare CephFS VFS support
  block:
    - name: Process OS specific tasks
      include_tasks: "{{ include_file }}"
      vars:
        prefix: "{{ role_path }}/tasks/cephfs/"
      with_first_found:
        - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
      loop_control:
        loop_var: include_file

    - name: SELinux - Allow Samba to do tcp socket operations
      seboolean:
        # Name of the boolean is misleading in this context.
        # https://github.com/samba-in-kubernetes/sit-environment/issues/79
        name: samba_load_libgfapi
        state: yes
        persistent: yes

    - name: Skip check of share path
      lineinfile:
        path: "{{ config.paths.ctdb.etc }}/events/legacy/50.samba.options"
        create: true
        search_string: "CTDB_SAMBA_SKIP_SHARE_CHECK"
        line: "CTDB_SAMBA_SKIP_SHARE_CHECK=yes"
        state: present

- name: Temporarily allow cap_dac_override for smbd from SELinux
  block:
    - name: Remove any existing policy package
      command: semodule -r smbd_dac_override
      failed_when: false

    - name: Copy required type enforcement file
      copy:
        src: smbd_dac_override.te
        dest: /tmp

    - name: Compile SELinux module file
      command: checkmodule -M -m -o smbd_dac_override.mod smbd_dac_override.te
      args:
        chdir: /tmp

    - name: Build SELinux policy package
      command: semodule_package -o smbd_dac_override.pp -m smbd_dac_override.mod
      args:
        chdir: /tmp

    - name: Load SELinux policy package
      command: semodule -i smbd_dac_override.pp
      args:
        chdir: /tmp

    - name: Remove temporary policy files
      file:
        path: /tmp/smbd_dac_override.*
        state: absent
