---
- name: Prepare CephFS VFS support
  block:
    - name: Process OS specific tasks
      include_tasks: "{{ include_file }}"
      vars:
        prefix: "{{ role_path }}/tasks/cephfs/"
      with_first_found:
        - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
      loop_control:
        loop_var: include_file

    - name: SELinux - Allow Samba to do tcp socket operations
      seboolean:
        # Name of the boolean is misleading in this context.
        # https://github.com/samba-in-kubernetes/sit-environment/issues/79
        name: samba_load_libgfapi
        state: yes
        persistent: yes

    - name: Skip check of share path
      lineinfile:
        path: "{{ config.paths.ctdb.etc }}/events/legacy/50.samba.options"
        create: true
        search_string: "CTDB_SAMBA_SKIP_SHARE_CHECK"
        line: "CTDB_SAMBA_SKIP_SHARE_CHECK=yes"
        state: present

    # We create the socket under /run/samba/ to avoid SELinux AVC denial
    # https://github.com/samba-in-kubernetes/sit-environment/pull/128#issuecomment-2624527331
    - name: Run libcephfsd for proxy
      shell: >
        LIBCEPHFSD_SOCKET=/run/samba/libcephfsd.sock nohup
        /usr/sbin/libcephfsd < /dev/null &> /var/log/ceph/libcephfsd.log &

- name: Temporarily allow cap_dac_override for smbd from SELinux
  include_tasks: custom_selinux_policy.yml
  vars:
    module_name: "{{ item }}"
  with_items:
    - smbd_dac_override
    - smbd_connect_proxy
