---
- name: Prepare CephFS VFS support
  when: config.be.variant == 'vfs'
  block:
    - name: Process OS specific tasks
      include_tasks: "{{ include_file }}"
      vars:
        prefix: "{{ role_path }}/tasks/cephfs/"
      with_first_found:
        - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
      loop_control:
        loop_var: include_file

    - name: SELinux - Allow Samba to do tcp socket operations
      seboolean:
        # Name of the boolean is misleading in this context.
        # https://github.com/samba-in-kubernetes/sit-environment/issues/79
        name: samba_load_libgfapi
        state: yes
        persistent: yes

    - name: Install CephFS VFS module
      yum:
        name: samba-vfs-cephfs
        state: present

    - name: Skip check of share path
      lineinfile:
        path: "{{ config.paths.ctdb.etc }}/events/legacy/50.samba.options"
        create: true
        search_string: "CTDB_SAMBA_SKIP_SHARE_CHECK"
        line: "CTDB_SAMBA_SKIP_SHARE_CHECK=yes"
        state: present
