---
- name: Prepare CephFS VFS support
  when: config.be.variant == 'vfs'
  block:
    - name: Install CephFS VFS module
      yum:
        name: samba-vfs-cephfs
        state: present

    - name: Set selinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Skip check of share path
      lineinfile:
        path: "{{ config.paths.ctdb.etc }}/events/legacy/50.samba.options"
        create: true
        search_string: "CTDB_SAMBA_SKIP_SHARE_CHECK"
        line: "CTDB_SAMBA_SKIP_SHARE_CHECK=yes"
        state: present
