---
- name: Copy necessary configuration directories
  shell: cp -r {{ item }} {{ config.configdir }}
  with_items:
    - /etc/ceph
    - /etc/samba
    - /etc/ctdb
  when: inventory_hostname in groups['cluster']
