---
- hosts: cluster
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
    - cluster-{{ config.be.name }}.yml
  roles:
    - common.prep
    - node.prep
    - "sit.{{ config.be.name }}"
    - ctdb.setup
    - samba.setup
