- hosts: cluster
  become: yes
  become_method: sudo
  vars_files:
    - distro-vars.yml
    - cluster-vars.yml
  roles:
    - common.prep
    - node.prep
    - "sit.{{ backend }}"
    - ctdb.setup
    - samba.setup
