---
- name: Process {{ config.be.name }} specific tasks (git_configure)
  include_tasks:
    file: "{{ backend_dir }}/configure.yml"
  vars:
    backend_dir: "{{ role_path }}/tasks/{{ config.be.name }}/git"
