---
- name: Temporarily allow access for smbd and/or ctdbd from SELinux
  include_tasks: custom_selinux_policy.yml
  vars:
    module_name: "{{ item }}"
  with_items:
    - smbd_dac_override
    - ctdbd_smbd_pid
