---
- name: Install yum copr plugin
  yum:
    name: yum-plugin-copr
    state: latest

- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/setup/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[config.nodes[inventory_hostname].os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file
