---
- name: Process samba users
  include_tasks: create_users.yml
  vars:
    accounts: "{{ account_group.value.users | default({}, true) }}"
  when: account_group.key in site.accounts
  with_items: "{{ config.accounts | dict2items }}"
  loop_control:
    loop_var: account_group
  run_once: yes
