- name: Install required packages
  yum:
    name:
      - cifs-utils
      - samba-test
      - python-pip
      - git
      - make
    state: latest

- name: Install Python 3 modules
  pip:
    executable: /usr/bin/pip3
    name:
      - PyYAML
      - iso8601
    extra_args: --ignore-installed
