- name: Install required packages
  yum:
    name:
      - cifs-utils
      - samba-test
      - python3-pip
      - git
      - make
      - python3-pytest
    state: latest

- name: Install Python 3 modules
  pip:
    executable: /usr/bin/pip3
    name:
      - PyYAML
      - iso8601
    extra_args: --ignore-installed

- name: Link to pytest
  file:
    src: /usr/bin/pytest-3
    dest: /usr/local/bin/pytest
    state: link
