---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os.includes }}"
  loop_control:
    loop_var: include_file

- name: Process backend specific tasks (client)
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: client/main.yml

- debug:
    msg: "{{ ctdb_network_public_interfaces }}"

- name: Create a README file
  template:
    src: README.j2
    dest: /root/README
    owner: root
    group: root
    mode: '0644'

- name: Create the test-info.yml file with test cluster information
  template:
    src: test-info.yml.j2
    dest: /root/test-info.yml
  vars:
    private_interfaces: "{{ ctdb_network_private_interfaces }}"
    public_interfaces: "{{ ctdb_network_public_interfaces }}"
    exported_sharenames: "{{ samba_shares| map(attribute='share_name') | list }}"
    test_users: "{{ samba_users }}"
    test_backend: "{{ config.be.name }}"
