---
- name: Create Samba user
  shell: >-
    (echo {{ accounts[item].password }}; echo {{ accounts[item].password }}) |
      smbpasswd -a {{ item }}
  when: accounts[item].samba
  with_items: "{{ accounts }}"
