---
- name: Process samba users
  include_tasks: create_users.yml
  vars:
    accounts: "{{ config.accounts[account_group].users }}"
  when:
    - config.accounts[account_group].users
    - account_group in config.nodes[inventory_hostname].accounts
  with_items: "{{ config.accounts }}"
  loop_control:
    loop_var: account_group
  run_once: yes
