---
- name: Copy necessary configuration directories
  shell: cp -r {{ item }} {{ config.configdir }}
  with_items:
    - "{{ config.paths.samba.etc }}"
    - "{{ config.paths.ctdb.etc }}"
  when: inventory_hostname in groups['cluster']
