---
- name: Provision all machines
  include_role:
    name: "provisioner.{{ provisioner_name }}"
    tasks_from: "{{ provision_action }}/main.yml"
  vars:
    data: "{{ config.provisioners[provisioner_name] }}"
  loop: "{{ config.provisioners.keys() }}"
  loop_control:
    loop_var: provisioner_name
