---
- name: Preparing environment
  delegate_to: localhost
  connection: local
  become: false
  block:
    - name: Provision machines
      include_role:
        name: "provisioner.{{ site.provisioner }}"
        tasks_from: "{{ provision_action }}/main.yml"
      vars:
        data: "{{ config.provisioners[site.provisioner] }}"
