---
- name: Preparing environment
  delegate_to: localhost
  connection: local
  become: false
  block:
    - name: Provision machines
      include_role:
        name: "provisioner.{{ site.provisioner }}"
        tasks_from: "{{ provision_action }}/main.yml"
      vars:
        data: "{{ config.provisioners[site.provisioner] }}"
        ssh_key_pub: "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"

    - name: Generate local files
      when: provision_action == 'create'
      run_once: true
      block:
        - name: Generate inventory file
          template:
            src: site_inventory.j2
            dest: ansible/site_inventory

        - name: Generate SSH config file
          template:
            src: ssh_config.j2
            dest: ansible/ssh_config

    - name: Cleanup files
      when: provision_action == 'destroy'
      run_once: true
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ansible/site_inventory
        - ansible/ssh_config

- name: Configure machines
  when: provision_action == 'create'
  block:
    - name: Create .site directory in machines
      file:
        path: ~/.site
        mode: 0700
        state: directory

    - name: Copy SSH private key
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "{{ item }}/id_rsa"
        mode: 0600
      with_items:
        - ~/.site
        - ~/.ssh

    - name: Copy SSH public key
      copy:
        src: "{{ ansible_ssh_private_key_file + '.pub'}}"
        dest: "{{ item }}/id_rsa.pub"
        mode: 0600
      with_items:
        - ~/.site
        - ~/.ssh

    - name: Copy SSH config file
      copy:
        src: "ansible/ssh_config"
        dest: "~/.ssh/config"
        mode: 0600
