---
- name: Generate config.yml in ansible directory
  template:
    src: config.yml.j2
    dest: ./ansible/config.yml
  vars:
    os: "{{ use_distro | default('centos8') }}"
    be: "{{ backend | default('glusterfs') }}"

- name: Load configuration
  include_vars:
    file: "ansible/config.yml"

- debug:
    var: config
