---
- name: add copr to get gluster-ansible
  command: yum -y copr enable godas/gluster-ansible

- name: Install gluster-ansible
  yum:
    name:
      - ansible-core
      - gluster-ansible-cluster
      - gluster-ansible-features
      - gluster-ansible-infra
      - gluster-ansible-maintenance
      - gluster-ansible-repositories
    state: latest

- name: Install required ansible collections
  become: no
  shell: ansible-galaxy collection install {{ item }}
  loop:
    - ansible.posix
    - community.general
    - gluster.gluster
    - ovirt.ovirt
