- name: Install yum copr plugin
  yum:
    name: yum-plugin-copr
    state: latest

- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  with_first_found:
    - files: "{{ config.os.includes }}"
  loop_control:
    loop_var: include_file
