#!/bin/bash

dnf install -y \
    "@Development Tools" \
    avahi-devel \
    bind \
    bison \
    cups-devel \
    dbus-devel \
    docbook-style-xsl \
    e2fsprogs-devel \
    flex \
    gcc \
    gawk \
    glibc-gconv-extra \
    gnupg2 \
    gnutls-devel \
    gpgme-devel \
    jansson-devel \
    krb5-devel \
    krb5-server \
    libacl-devel \
    libaio-devel \
    libarchive-devel \
    libattr-devel \
    libcap-devel \
    libcmocka-devel \
    libicu-devel \
    libtasn1-devel \
    libtasn1-tools \
    libtirpc-devel \
    liburing-devel \
    libuuid-devel \
    libxslt \
    lmdb \
    lmdb-devel \
    make \
    mingw32-gcc \
    mingw64-gcc \
    ncurses-devel \
    openldap-devel \
    pam-devel \
    'perl(Archive::Tar)' \
    'perl(ExtUtils::MakeMaker)' \
    'perl(FindBin)' \
    perl-interpreter \
    'perl(Parse::Yapp)' \
    'perl(Test::More)' \
    perl-generators \
    popt-devel \
    python3-cryptography \
    python3-dateutil \
    python3-devel \
    python3-dns \
    python3-gpg \
    python3-iso8601 \
    python3-markdown \
    python3-pyasn1 \
    python3-requests \
    python3-setproctitle \
    python3-setuptools \
    quota-devel \
    readline-devel \
    rpcgen \
    rpcsvc-proto-devel \
    systemd-devel \
    systemd-rpm-macros \
    xfsprogs-devel \
    xz \
    zlib-devel
