---
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - update.inventory

- hosts: site
  gather_facts: false
  vars:
    provision_action: destroy
  roles:
    - load.config
    - local.provision

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - local.clean
