---
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - update.inventory

- hosts: clients
  become: yes
  become_method: sudo
  roles:
    - load.config
    - tests
