---
#
# Update all nodes
#
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - update.inventory

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - load.config
    - hosts.update
