---
- hosts: localhost
  connection: local
  become: no
  roles:
    - local.defaults
    - update.inventory

- hosts: site
  gather_facts: false
  vars:
    provision_action: create
  roles:
    - load.config
    - local.provision
