---
- hosts: localhost
  connection: local
  become: no
  roles:
    - local.defaults

- hosts: site
  gather_facts: false
  vars:
    provision_action: create
  vars_files:
    - "{{ site_dir }}/config.yml"
  roles:
    - local.provision
