
define HELP_TEXT
  test           Create, build and test a site
  statedump      Dump the state of the site
endef
export HELP_TEXT

ifneq ($(filter-out help,$(MAKECMDGOALS)),)
ifndef VIRTUAL_ENV
$(error Site's Makefile must be called inside a Python virtual environment)
endif
endif

.PHONY: test
test: setup.site

.PHONY: statedump
statedump: nodes.statedump

.PHONY: help
help:
	@cat <<< "$${HELP_TEXT}"

ANSIBLE_EXTRA_VARS := -e 'site_dir=${SITE_DIR} ${EXTRA_VARS}'

ansible = ansible-playbook --inventory localhost, $(addprefix --tags ,$(1)) \
			$(ANSIBLE_EXTRA_VARS) $(BASE)/site.yml

local:
	@$(call ansible,initialize)

hosts.update.only:
	@$(call ansible,update)

setup.prep.only:
	@$(call ansible,prepare)

setup.prep:
	@$(call ansible,initialize update prepare)

setup.cluster.only:
	@$(call ansible,cluster)

setup.cluster:
	@$(call ansible,initialize update prepare cluster)

setup.clients:
	@$(call ansible,clients)

generate.report:
	@$(call ansible,report)

nodes.statedump:
	@$(call ansible,statedump)

client.test:
	@$(call ansible,test)

setup.site:
	@$(call ansible,initialize update prepare cluster clients report test)

clean:
	@$(call ansible,cleanup)

.PHONY: local hosts.update.only setup.prep.only setup.prep setup.test.only setup.cluster.only setup.cluster setup.clients client.test setup.site clean
