
define HELP_TEXT
  test           Create, build and test a site
  statedump      Dump the state of the site
endef
export HELP_TEXT

ifneq ($(filter-out help,$(MAKECMDGOALS)),)
ifndef VIRTUAL_ENV
$(error Site's Makefile must be called inside a Python virtual environment)
endif
endif

.PHONY: test
test: setup.site

.PHONY: statedump
statedump: nodes.statedump

.PHONY: help
help:
	@cat <<< "$${HELP_TEXT}"

INVENTORY := $(BASE)/ansible/site_inventory

ifdef EXTRA_VARS
	ANSIBLE_EXTRA_VARS := -e '${EXTRA_VARS}'
endif

local:
	@ansible-playbook --inventory localhost, ${ANSIBLE_EXTRA_VARS} $(BASE)/local.yml

hosts.update.only:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/hosts.update.yml

setup.prep.only:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/setup.prep.yml

setup.prep: local hosts.update.only setup.prep.only

setup.prep.copy:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} --start-at-task "copy ansible playbooks to setup machine" $(BASE)/setup.prep.yml

setup.cluster.only:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/setup-cluster.yml

setup.cluster: setup.prep setup.cluster.only

setup.clients:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/setup-clients.yml

generate.report:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/generate-report.yml

nodes.statedump:
	@ansible-playbook --inventory $(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/nodes.statedump.yml

client.test:
	@ansible-playbook --inventory=$(INVENTORY) ${ANSIBLE_EXTRA_VARS} $(BASE)/client-test.yml

setup.site: setup.cluster setup.clients generate.report client.test

clean:
	@ansible-playbook --inventory localhost, ${ANSIBLE_EXTRA_VARS} $(BASE)/cleanup.yml

.PHONY: local hosts.update.only setup.prep.only setup.prep setup.test.only setup.cluster.only setup.cluster setup.clients client.test setup.site clean
