---
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - update.inventory

- hosts: site
  become: yes
  become_method: sudo
  roles:
    - load.config
    - logs.collect
    - config.collect
