---
- name: Destroy vagrant machines
  command: vagrant destroy -f

- name: Remove vagrant settings
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - .vagrant
    - Vagrantfile
    - ansible/site_inventory
    - ansible/ssh-config-setup
    - site_inventory
    - ssh-config-host
