---
- name: Destroy vagrant machines
  command:
    chdir: "{{ config.home }}"
    cmd: vagrant destroy -f

- name: Remove vagrant settings
  file:
    path: "{{ config.home }}/{{ item }}"
    state: absent
  with_items:
    - .vagrant
    - Vagrantfile
    - site_inventory
    - site_inventory_setup
    - ssh-config-host
    - ssh-config-setup
