---
- name: update packages
  yum:
    name: '*'
    state: latest

- name: Enable EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Install Python2 pip
  yum:
    name: python2-pip
    state: installed

- name: Install pip jinja2 library
  pip:
    name: jinja2
    state: latest
