---
- name: Load global configuration
  include_vars:
    file: "{{ site_dir }}/config.yml"

- name: Update the inventory
  add_host:
    name: "{{ item }}"
    ansible_python_interpreter: /usr/bin/python3
    groups: "{{ config.nodes[item].groups + ['site'] }}"
    site: "{{ config.nodes[item] }}"
  with_items: "{{ config.nodes.keys() }}"

- name: Create state directory structure on host
  file:
    path: "{{ config.statedir }}/{{ item }}"
    state: directory
  loop: "{{ groups['site'] }}"

- name: Copy common playbook configuration
  copy:
    src: "{{ site_dir }}/config.yml"
    dest: "{{ config.statedir }}"
