---
- name: Preparing environment
  delegate_to: localhost
  connection: local
  become: false
  block:
    - name: Provision machines
      include_role:
        name: "provisioner.{{ site.provisioner }}"
        tasks_from: "{{ provision_action }}/main.yml"
      vars:
        data: "{{ config.provisioners[site.provisioner] }}"
        ssh_key_pub: "{{ lookup('file', site_dir + '/ssh/id_rsa.pub') }}"

    - name: Generate local files
      when: provision_action == 'create'
      run_once: true
      block:
        - name: Generate SSH config file
          template:
            src: ssh_config.j2
            dest: "{{ site_dir }}/ssh/config"

    - name: Cleanup files
      when: provision_action == 'destroy'
      run_once: true
      file:
        path: "{{ site_dir }}/ssh/config"
        state: absent

- name: Configure machines
  when: provision_action == 'create'
  block:
    - name: Copy SSH private key
      copy:
        src: "{{ site_dir }}/ssh/id_rsa"
        dest: ~/.ssh/id_rsa
        mode: 0600

    - name: Copy SSH public key
      copy:
        src: "{{ site_dir }}/ssh/id_rsa.pub"
        dest: ~/.ssh/id_rsa.pub
        mode: 0600

    - name: Authorize SSH key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', site_dir + '/ssh/id_rsa.pub') }}"

    - name: Copy SSH config file
      copy:
        src: "{{ site_dir }}/ssh/config"
        dest: "~/.ssh/config"
        mode: 0600

    - name: Update SSH IdentityFile path
      replace:
        path: "~/.ssh/config"
        regexp: '^(\s*IdentityFile)\s.*'
        replace: "\\1 ~/.ssh/id_rsa"
