---
# required for python3-pyxattr
- name: Enable CRB repo
  command: dnf config-manager --set-enabled crb

- name: Enable EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Enable Samba nightly rpms repository
  command: >-
    yum-config-manager --add-repo {{ site.install.samba.url }}
  when: site.install.samba.type == 'repo'
