---
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - local.defaults

- hosts: site
  gather_facts: false
  vars:
    provision_action: destroy
  vars_files:
    - ansible/config.yml
  roles:
    - local.provision

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - local.clean
