---
- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  vars_files:
    - "{{ lookup('env', 'SITE_HOME') | default('.') }}/config.yml"
  vars:
    provision_action: destroy
  roles:
    - local.provision

- hosts: localhost
  connection: local
  become: no
  gather_facts: false
  roles:
    - local.clean
