---
- name: Create the ctdb shared subvolume
  when: config.data.ctdb_mutex is not defined
  include_role:
    name: 'sit.{{ config.be.name }}'
    tasks_from: new_volume
  vars:
    name: "ctdb"
    path: "{{ ctdb_lock_path }}"
