---
- name: Copy necessary configuration directories
  shell: cp -r {{ item }} {{ config.configdir }}
  with_items:
    - /etc/ceph
    - "{{ config.paths.samba.etc }}"
    - "{{ config.paths.ctdb.etc }}"
