---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/glusterfs/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[site.os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes

- name: Temporarily allow access on smbd_var_run_t for ctdbd from SELinux
  include_tasks: custom_selinux_policy.yml
  vars:
    module_name: ctdbd_smbd_pid
