---
- name: Run tests
  command:
    chdir: /root/sit-test-cases
    cmd: make test
  when: test_sanity_only is undefined

- name: Run sanity tests
  command:
    chdir: /root/sit-test-cases
    cmd: make sanity_test
  when: test_sanity_only is defined
