---
- name: Process backend specific tasks
  include_tasks: "{{ config.be.name }}/main.yml"

- name: Enable firewall for samba
  firewalld:
    service: samba
    permanent: yes
    state: enabled

- name: Reload firewall
  command: firewall-cmd --reload

- name: Create fresh directory /etc/samba/smb.shares to contain share definition
  block:
    - file:
        path: /etc/samba/smb.shares/
        state: absent
    - file:
        path: /etc/samba/smb.shares/
        state: directory
        mode: '0755'

- name: Create smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Add share configuration
  block:
    - name: Create the share configuration using backend
      include_role:
        name: 'sit.{{ config.be.name }}'
        tasks_from: new_share.yml
      vars:
        path: "{{ item.cluster_volume }}"
        file: "/etc/samba/smb.shares/{{ name }}.conf"
      with_items: "{{ samba_shares }}"

    - name: Include share configuration into smb.conf
      lineinfile:
        path: "/etc/samba/smb.conf"
        line: "include = /etc/samba/smb.shares/{{ name }}.conf"
        insertafter: EOF
      with_items: "{{ samba_shares }}"
  vars:
    name: '{{ item.share_name }}-{{ config.be.name }}-{{ config.be.variant }}'

- name: Create test users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    state: present
  with_items: "{{ samba_users }}"
